[package]
name = "cyudo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.9.0"
rand = "0.8.4"
console = "0.15.0"
nix = "0.23.1"